# Generated by Django 2.0.13 on 2020-06-09 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200604_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_pic',
            field=models.ImageField(blank=True, upload_to='blog_pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 11, 59, 26, 827727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 11, 59, 26, 826724, tzinfo=utc)),
        ),
    ]
