# Generated by Django 2.0.13 on 2020-06-09 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200609_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 23, 25, 725812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_pic',
            field=models.ImageField(blank=True, default='blog_pics/django-logo-negative.png', upload_to='blog_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 23, 25, 723751, tzinfo=utc)),
        ),
    ]
