# Generated by Django 2.0.13 on 2020-06-10 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20200610_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 21, 11, 19, 20410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 21, 11, 19, 18411, tzinfo=utc)),
        ),
    ]
