# Generated by Django 2.0.13 on 2020-07-16 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20200703_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_pic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_pic_1',
            field=models.ImageField(blank=True, default='blog_pics/django-logo-negative.png', upload_to='blog_pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_pic_2',
            field=models.ImageField(blank=True, upload_to='blog_pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_pic_3',
            field=models.ImageField(blank=True, upload_to='blog_pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='blogger_name',
            field=models.CharField(default='BloggerName', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='text_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text_3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 15, 12, 50, 108166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 15, 12, 50, 108166, tzinfo=utc)),
        ),
    ]
