# Generated by Django 2.0.13 on 2020-07-17 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_auto_20200716_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 6, 32, 53, 900671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 6, 32, 53, 899671, tzinfo=utc)),
        ),
    ]
