# Generated by Django 2.0.13 on 2020-07-28 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_auto_20200717_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 11, 7, 34, 188962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 11, 7, 34, 188962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
