# Generated by Django 2.0.13 on 2020-07-28 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0018_auto_20200728_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 11, 47, 0, 498372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_pic_1',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 11, 47, 0, 482746, tzinfo=utc)),
        ),
    ]
