# Generated by Django 2.0.13 on 2020-07-28 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0019_auto_20200728_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 11, 48, 49, 533786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_pic_1',
            field=models.ImageField(blank=True, default='blog_pics/django-logo-negative.png', null=True, upload_to='blog_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 11, 48, 49, 533786, tzinfo=utc)),
        ),
    ]
